# Generated by Django 5.2.1 on 2025-10-08 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_pengaduan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengaduan',
        ),
    ]
