# Generated by Django 5.2.1 on 2025-10-08 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0004_pengaduan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengaduan',
            name='judul',
        ),
    ]
