# Generated by Django 5.2.1 on 2025-10-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0005_remove_pengaduan_judul'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengaduan',
        ),
    ]
